name: DevMatchTests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  backend:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18.x'
    - name: Install dependencies with clean install
      run: npm ci
      working-directory: serverless
    - name: Run devmatch tests
      run: npm run test
      working-directory: serverless
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: serverless/test-results.json
  # frontend:
  #   timeout-minutes: 5
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v2
  #     with:
  #       node-version: '18.x'
  #   - name: Install dependencies with clean install
  #     run: npm ci
  #     working-directory: client
  #   - name: Run devmatch tests
  #     run: npm run test
  #     working-directory: client
  #   - uses: actions/upload-artifact@v3
  #     if: always()
  #     with:
  #       name: frontend-results
  #       path: client/test-results.json
